### ISSUE TITLE
Edit the XSLT Assignments

### ISSUE THREAD

**Issue by RJP43** [ebeshero/newtFire-webDev#13]
We (@nlottig94 @ebeshero and I) discussed at lunch today (1/6) that since the students of the Spring 2016 course will only be getting three of the seven XSLT assignments that we might want to rewrite either [XSLT 2](http://newtfire.org/dh/XSLTExercise2.html) or [XSLT 4](http://newtfire.org/dh/XSLTExercise4.html) to include Modal XSLT (like we use in [XSLT](http://newtfire.org/dh/XSLTExercise5.html)).

**Comment by ebeshero** [comment]
All: We've no XSLT Exercise 2 yet...I need to remember what I thought I was doing with this...

**Comment by RJP43** [comment]
I have been working on this and will have a first draft ready for review by the end of the day.

**Comment by RJP43** [comment]
@ebeshero just a reminder we need to edit the [syllabus](http://newtfire.org/dh/CDVSyll.html#d2016-02-26) so the [new XSLT 2](https://github.com/ebeshero/newtFire-webDev/blob/master/cdv-course/XSLTExercise2_CDV.html) shows for the assignment on 2-26. Also need to assign students to review [Obdurodon's tutorial on Modal XSLT](http://dh.obdurodon.org/modal-xslt.html) along with David's [Attribute Value Template Tutorial](http://dh.obdurodon.org/avt.xhtml). Finally have to make sure we upload the edited XSLT Exercise 4 for the CDA course and the [new Source Document XML]() that corresponds with both of those exercises.

Still editing XSLT Exercise 3 for CDV.

**Comment by ebeshero** [comment]
- [x] Update Ex 1 for CDV: Require the numbering of book and chapter divs: just need to merge Becca's pull request
- [x] Review and add the XSLTExercise1_CDV.html to newtFire.
- [x] Update syllabus to include Modal XSLT tutorial early as a reading to support XSLT Ex 3
- [x] Review new XSLT Ex 2(CDV) and XSLT Ex 4(CDA) (see links below)
- [x] Update [source file - NelsonArticle_1888-07-30.xml](https://github.com/ebeshero/newtFire-webDev/blob/master/dh-courses-Common/NelsonArticle_1888-07-30.xml) and **the two newly separate assignment files** for [CDA XSLT Ex 4 - XSLTExercise4.html](https://github.com/ebeshero/newtFire-webDev/blob/master/cda-course/XSLTExercise4.html) and [CDV XSLT Ex 2 - XSLTExercise2_CDV.html](https://github.com/ebeshero/newtFire-webDev/blob/master/cdv-course/XSLTExercise2_CDV.html) that work with the same source file. 
- [x] Rework / simplify solution to CDA XSLT Ex 4 or CDV XSLT Ex 2. 
- [ ] Update [CDA XSLT Ex 6 - XSLTExercise6.html](https://github.com/ebeshero/newtFire-webDev/blob/master/cda-course/XSLTExercise6.html) and the [output file - dickinson-output.html](https://github.com/ebeshero/newtFire-webDev/blob/master/dh-courses-Common/dickinson-output.html) and the [CSS - dickinsonStyle.css](https://github.com/ebeshero/newtFire-webDev/blob/master/dh-courses-Common/dickinsonStyle.css). Both the CSS and the output file will be the same two files referenced in XSLTExercise3_CDV.html which will be ready for review by Friday.
- [ ] Create topEditor SSI for editing/repurposing material from other pages. (not the same as authoring).
