### ISSUE TITLE
Revise XSLT Exercise 4 for CDV course

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/newtFire-webDev#14]
Currently the XSLT Ex 4 refers to XSLT Ex 3 (which we're not doing because we'll be making tables with XQuery this time). We need to revise this exercise a bit just for the CDV course, so maybe we'll give it a new file name just for the CDV course: XSLT-CDVEx3 should work. 

@RJP43 want to give this a try?

**Comment by RJP43** [comment]
Yes.

**Comment by ebeshero** [comment]
Thanks, Becca--shouldn't be too rough to fix.

**Comment by RJP43** [comment]
consider doing automatic numbering as we discussed in class 2015/01/11

**Comment by ebeshero** [comment]
Yes! Good idea...

**Comment by ebeshero** [comment]
@RJP43 Where are we with this? I'm surveying the XSLT materials...

**Comment by RJP43** [comment]
@ebeshero I have been working on XSLT exercise 2 this weekend by making a few revisions to  XSLT 4 to turn it into exercise 2. XSLT 2 I plan to have done today so we can begin the review process and XSLT 3,  which I am making out of XSLT 5 AND 6, I plan to finish by tomorrow. I will push everything I have done so far in a few hours.
