### ISSUE TITLE
Update SSI

### ISSUE THREAD

**Issue by RJP43** [ebeshero/newtFire-webDev#21]
@ebeshero this is just a reminder to add an author line (and maintained by line) to tutorials and assignments created by students so that we can link to this in our virtual resumes for the professional webpages we will be creating. Thanks :)

**Comment by ebeshero** [comment]
@RJP43 Done! To see your name in our new author line on the newtFire pages, see:
[XSLT Exercise 3](http://newtfire.org/dh/XSLTExercise3.html)
[XSLT Exercise 4](http://newtfire.org/dh/XSLTExercise4.html)
And @alexkrongel see [XPath Exercise 4](http://newtfire.org/dh/XpathExercise4.html)
Thank you! Let me know if you'd like me to change the e-mail address!
