### ISSUE TITLE
Edit HTML Exercise 1

### ISSUE THREAD

**Issue by RJP43** [ebeshero/newtFire-webDev#38]
We should edit HTML exercise 1 to include a section on file naming ... perhaps just work in the following section from the tutorial:
`By convention, the first page you place in a particular website folder is designated your index.html page. You don't have to have an index.html, but if you do, the main page of your site can be abbreviated to the name of the site directory holding the web files, like this one for my personal Pitt homepage: http://www.pitt.edu/~ebb8/ . By default, when given that address, the web browser retrieves the index.html file I have placed in that space, and if it doesn't find one it generates an error. (The site address leads to exactly the same place as http://www.pitt.edu/~ebb8/index.html .)`

**Comment by RJP43** [comment]
@ebeshero this change is waiting to be pulled in and added to newtFire. Then this issue can be closed.

**Comment by ebeshero** [comment]
@RJP43 Thanks, Becca. Go ahead a pull from this repo again: I just updated the page a little to add the new `<section>` elements (as seen in our new [House Style guide](http://newtfire.org/dh/housestyle.html), and changed straight apostrophes to curly apostrophes and a couple of little spot revisions...and posted on newtFire!

http://newtfire.org/dh/HTMLExercise1.html

**Comment by RJP43** [comment]
Great thanks!

**Comment by RJP43** [comment]
@ebeshero I have finished making my basic comments on HTML exercise 1 for the new students if you want to/have time to  run through them and comment so we get them back before they turn in Exercise 2
