### ISSUE TITLE
Regex Assignment Revision

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/newtFire-webDev#4]
I've just overhauled our last Regex assignment, and posted [the assignment on newtFire here](http://newtfire.org/dh/RegexExercisePlay.html). At first I thought we should try a transcript of a 1930s radio show, and I saved a copy of Orson Welles' 1938 _War of the Worlds_ as a good text, but this wasn't really an equivalent challenge to the Wilde play, since radio transcripts aren't divided into Acts and their structure isn't as complicated as what we see in a five-act stage play. (The only things to mark with regex in a radio show are simply speeches, speakers, and sound effect cues. I think this would make good exam material, but it's not quite challenging enough to follow our previous assignments.) Instead, I decided on a Gutenberg text of G. B. Shaw's play, _Pygmalion_. I like _Pygmalion_ for this assignment because it has a complex structure, with a prose preface and a long prose epilogue, but it's different from Wilde's _Importance of Being Earnest_ because there aren't scene divisions within the acts, and this text of _Pygmalion_ doesn't feature a cast list. So the regular expression work will look sufficiently different, I think, from Obdurodon's exercise.
## Tasks:
- I'd like @alexkrongel @andrewntz23 and @RJP43 to review the assignment and simply do the regex. 
- Do you spot errors, omissions, problems on the assignment page? Feel free to make corrections yourself on the file here in GitHub: Find the file in your cloned local GitHub in the dh-course directory as RegexExercisePlay.html. Push your changes and ping me here in Issues. Alert me here to any problems, or use line comments on the most recent uploaded version of the file here in GitHub: https://github.com/ebeshero/newtFire-webDev/blob/master/dh-course/RegexExercisePlay.html
- Would one of you volunteer to produce an official solution file? Name your solution file regex-play-solution.txt, be profuse with explanatory comments that take a student by the hand and walk step by step through your solution and why you did things the way you did. Save your file to a Dropbox folder  I'll share with you by e-mail. (We can't push the solution files to GitHub for obvious reasons.) Please respond here if you're willing to write up this solution. We'll stagger the solution writing so you each get a chance to write a solution which the others proofread.

Thanks, everyone! Let me know how this exercise looks to you!

**Comment by ebeshero** [comment]
I've set a milestone to give this a deadline of Tues. 9/29, but we'll only need to post the solution on Friday this week. Tuesday should give us plenty of time to review the solution together.

**Comment by ebeshero** [comment]
@RJP43 Becca: Shall we use your solution file for the Regex Voyage Narrative assignment (due on Wed.) as our posted solution file? Want to review it and see if it's good to share with the students tomorrow? Maybe add some comments to it to explain your thinking process in choosing particular regex patterns. Please rename your file regex-voyage-solution.txt and save in the new Solutions-to-Post directory in our course Dropbox. Thanks!

**Comment by RJP43** [comment]
@ebeshero @alexkrongel @andrewntz23 @ghbondar I finished revising my answers to the Regex Voyage Narrative assignment and saved the write up and a copy of what the XML should look like after completing Regex follwing my steps in the Solutions-to-Post.

**Comment by andrewntz23** [comment]
I'll draft up a solution. It should be done by tonight, but tomorrow at the very latest.

**Comment by ebeshero** [comment]
Thanks, Andrew!

**Comment by andrewntz23** [comment]
Just posted! It's in Github in solutions-to-post; I made a folder for RegEx assignment 4 like the one for 3.

**Comment by alexkrongel** [comment]
I played with the file and all looks well to me!

**Comment by ebeshero** [comment]
Thanks, @andrewntz23 ! I'm reviewing it now--thanks for the detail! I think I'll try saving your solution text in markdown as .md to control the formatting, and we'll want to take a pass through proofing it. @RJP43 Becca, want to proof this since we'll want to use it later this week in our class?

 I'm going to set @alexkrongel to work on a first wave of the [XPath assignment revision](https://github.com/ebeshero/newtFire-webDev/issues/5)--which is a bit of a bear (and we'll want some help from @andrewntz23 there, too).

**Comment by ebeshero** [comment]
@andrewntz23 @RJP43 @alexkrongel I started a new file containing Andrew's solution, and I'm preparing it in Markdown format, with the extension .md .  

This is designed so it'll open and be easily readable in GitHub as a "wiki" page, which is how I'd like to post the solutions.  May I ask that you make changes to the new .md document? I'm breaking it down into steps and adding a few formatting marks. (Follow the "Markdown supported" link here in GitHub above any comment window to get a feel for Markdown.)

**Comment by ebeshero** [comment]
I've posted [a GitHub wiki here](https://github.com/ebeshero/newtFire-webDev/wiki/Preparing-Markdown-Files-%28for-DH-assignment-solution-pages%29) with instructions on drafting and previewing solution pages in markdown. And I've reformatted @andrewntz23 's text file as .md: it looks pretty good! I'd like someone to walk through Andrew's steps and just see if you catch any typos if you implement this. I corrected one or two toward the end, but there could be others. @RJP43 would you take a look? We'd want to post this solution after Friday's class this week. 

I'd like to handle posting of solutions to homework assignments via GitHub. (I'll store all the solutions in a directory called "Solutions" and empty its contents after a class ends and before a new one begins. And we'll push Solution files there as we proceed with the course.)

**Comment by RJP43** [comment]
@ebeshero I made a couple of spelling corrections, but otherwise I think the soultion works great. The steps are clear and easy to follow. I will work on viewing the marked down version of the file when I return from work. Nice work @andrewntz23 :)

**Comment by alexkrongel** [comment]
@ebeshero Challenge accepted! I just got back from a rally I put on this morning, so I'll try to get that drafted by tonight or early tomorrow morning!

**Comment by ebeshero** [comment]
@andrewntz23 @RJP43 Great speedy work with writing the new Regex assignment and with drafting very detailed solutions for Regex! Our students are working with these now! Thank you!!!
