### ISSUE TITLE
Regex Test Grading

### ISSUE THREAD

**Issue by spadafour** [ebeshero/newtFire-webDev#55]
I'm missing the .xml document from Matt Burch. I can run his regex myself, but I figured I would ask. Also, I don't seem to have a solutions file in the folder for the test either. I can just figure out the answers myself, but I wouldn't mind taking a look at the answer key that someone made. @nlottig94 did you make the test? Was there an answer key with it?

**Comment by nlottig94** [comment]
@RJP43 made the regex test I think @spadafour. The solution might also be in the solutions folder on the DHClass-Hub.  Check there :)

**Comment by spadafour** [comment]
@RJP43 yeah I'm pretty sure the solution isn't posted at all. Am I just not digging in the right spot?

**Comment by nlottig94** [comment]
I'm not seeing it at all either @spadafour

**Comment by ebeshero** [comment]
@spadafour right--I don't think we made a key for this. I'm writing up a key quickly now. You may want to check my key against your own solution. I just now made a new Regex-Exam folder in the Dropbox folder we're using for Solutions-to-Post this semester.

**Comment by ebeshero** [comment]
@spadafour My solution is now saved in our Dropbox Solutions-to-Post folder.
