### ISSUE TITLE
Syllabus jumping?

### ISSUE THREAD

**Issue by RJP43** [ebeshero/newtFire-webDev#58]
For some reason the syllabus is jumping down to next week instead of this week... I thought it might have been just my browser so I tested it on another computer and then my iPad and then Matt tested it while I'm working with him and Lauren .... For all of us it is jumping a week ahead.

**Comment by ebeshero** [comment]
@RJP43 I can't duplicate the problem here. On Firefox and Chrome, I am properly jumping to 3/14. 

When you jump, copy the URL in the browser and paste it here. It should read, as mine does: http://newtfire.org/dh/CDVSyll.html#d2016-03-14

**Comment by ebeshero** [comment]
And I am properly jumping to that date on Safari on my iPad, too.

**Comment by RJP43** [comment]
Ahh ok it is working ... I'm sorry!
