### ISSUE TITLE
XQuery Exercise 2

### ISSUE THREAD

**Issue by RJP43** [ebeshero/newtFire-webDev#59]
In question `#4`bullet point `#4` might want to out right say to define a new variable that has the dereferencing predicate... also Matt suggested in class to possibly add a visualization to help explain what it is that is being found.

**Comment by RJP43** [comment]
correct that you want to order by the distinct `@ref` that is most frequently referenced instead of descending alphabetical order (which is currently what is being asked on the assignment)

so `order by count($peep) descending`
instead of `order by $peep descending`

**Comment by ebeshero** [comment]
Made the correction to `order by`.

**Comment by ebeshero** [comment]
And changed language to say we want to make a new variable that checks/indexes.
