### ISSUE TITLE
XSLT 3 and 4 (our 4 and 5): Modal XSLT and AVTs

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/newtFire-webDev#7]
I'd thought that the Mitford Site Index would be a suitable replacement for Shakespeare's sonnets, but I'm not sure it makes much sense to generate a table of contents, and then sort the Site Index (which is already sorted. A series of poems would be more interesting and make the assignment re-writing a little easier.

I think we might work with my Emily Dickinson project site and introduce work with the collection() function, since my Dickinson poems in Fascicle 16 are each coded in a separate file. This would add something new to the assignments in Obdurodon, to indicate how to extract only the poem portions of each file from the TEI and then output information about them in alphabetical order. 

Students will need to access the collection of poems via cloning the Dickinson project site.

**Comment by RJP43** [comment]
Okay, @ebeshero I have just completed my rewrite for XSLT exercise 4 using AVTs. The html page is sitting inside of GitHub and there is also a copy inside of the Dropbox folder. The Dropbox folder is also holding  my solution XSLT and CSS style-sheets as well as a copy of the results from the transformation saved as a html document. Finally, I uploaded the revised XML source document to this GitHub and  there is a copy of that inside of the Dropbox folder as well.
