### ISSUE TITLE
Greensburg vs. Oakland Grading Debate

### ISSUE THREAD

**Issue by amk231** [ebeshero/newtFire-webDev#97]
In my experience in Oakland’s digital humanities course I often found myself wondering if I was performing as well as the other students in my class and whether or not my homework assignments were done well or merely just satisfactory. I found it difficult to base my progress off of the check, check plus system because it seemed as if everyone was receiving the same grades throughout the semester. 

I understand that many students may have anxiety about entering this course, especially for those in which this will be their first coding experience (like me!). The Oakland grading system is very forgiving, which relieved an incredible amount of stress of failure, because even if you could not figure out a portion of the homework, you could still receive a check, like the rest of the students who did figure it out. Though this is a fair system for a hardworking student, this system can also allow for less ambitious students to get by as well as other students without putting in the same amount of work.

I also think that having a larger spectrum of points is more beneficial because it allows the student to tell exactly how well they are performing not just in comparison to their peers, but also to themselves. I do not believe that the Greensburg system will distract much, if at all, from personal growth and in fact would motivate students to go the extra mile in their assignments because they will actually see the result of their work. And from what I saw in your reply to Zach’s comment, students will be receiving reassuringly high points if they work hard, so I do not think students’ grades will suffer. All in all, though I can appreciate the benefits of the Oakland system, I strongly lean towards the Greensburg version.

**Comment by ghbondar** [comment]
Thanks for your response, Angela! Please see the thread started by Zach #96 for more thorough feedback from Elisa and myself, with more to follow no doubt!
